format_version: 3
pipelines:
  build_and_publish_image:
    group: sample
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials: 
      git: 
        url: https://github.com/seu-usuario/simple-app.git 
        branch: main
    stages:
      - build_stage:
          fetch_materials: true
          jobs:
            build_image:
              elastic_profile_id: demo-app
              artifacts:
                - external:
                    id: bulletin-board
                    store_id: dockerhub
                    configuration:
                      options:
                        Image: ${DOCKERHUB_USERNAME}/bulletin-board
                        Tag: ${GO_PIPELINE_LABEL}
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Building Docker image..."
                        docker build -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL . -f Dockerfile.application
                        echo "Pushing Docker image..."
                        docker push $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL
