format_version: 3
pipelines:
  MEU_build_and_publish_image:
    group: sample
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
    materials:
      git:
        git: https://github.com/alvaroconceicaocrossjoin/simple-app
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - MEU_build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build_image:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: bulletin-board
                store_id: dockerhub
                configuration:
                  options:
                    Image: ${DOCKERHUB_USERNAME}/bulletin-board
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL . -f Dockerfile
                command: /bin/bash
                run_if: passed
          install_kubectl:
            timeout: 0
            elastic_profile_id: kubectl_ubuntu
            tasks:
            - exec:
                arguments:
                - -c
                - |
                  curl -LO https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
                  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
                  echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
                command: /bin/bash
                run_if: passed
          build_deploy:
            timeout: 0
            elastic_profile_id: kubectl_ubuntu
            tasks:
            - exec:
                arguments:
                - -c
                - kubectl apply -f k8s-deployment.yaml
                command: /bin/bash
                run_if: passed
