format_version: 3
pipelines:
  deploy_to_k8s:
    group: simple
    label_template: ${COUNT}
    materials:
      dependency:
        pipeline: build_and_push
        stage: build
        job: build_image
    stages:
      - deploy:
          jobs:
            deploy_app:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        NAMESPACE="default"
                        DEPLOYMENT_NAME="simple-app"
                        IMAGE="$DOCKERHUB_USERNAME/simple-app:$GO_DEPENDENCY_LABEL_UPSTREAM"

                        echo "Deploying to Kubernetes..."
                        if kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE &>/dev/null; then
                          kubectl set image deployment/$DEPLOYMENT_NAME app-container=$IMAGE -n $NAMESPACE
                        else
                          kubectl create deployment $DEPLOYMENT_NAME --image=$IMAGE -n $NAMESPACE
                          kubectl expose deployment $DEPLOYMENT_NAME --type=NodePort --port=8080 -n $NAMESPACE
                        fi
